apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "matomo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "matomo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "matomo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.matomoNginx.image.repository }}:{{ .Values.matomoNginx.image.tag }}"
          imagePullPolicy: {{ .Values.matomoNginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /plugins/Morpheus/images/logo.png
              port: http
          readinessProbe:
            httpGet:
              path: /plugins/Morpheus/images/logo.png
              port: http
          resources:
            {{- toYaml .Values.matomoNginx.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: config
            - mountPath: /var/www/html
              name: html-files
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "matomo.fullname" . }}
          env:
            - name: "MATOMO_DATABASE_ADAPTER"
              value: "mysql"
            - name: "MATOMO_DATABASE_HOST"
              value:  {{ include "matomo.mariadb.fullname" . }}
            - name: "MATOMO_DATABASE_TABLES_PREFIX"
              value: "matomo_"
            - name: "MATOMO_DATABASE_USERNAME"
              value: "matomo"
            - name: "MATOMO_DATABASE_DBNAME"
              value: "matomo"
            - name: "MATOMO_DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ include "matomo.mariadb.fullname" . }}
                  key: "mariadb-password"
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: fastcgi
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: fastcgi
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/www/html
              name: html-files
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "matomo.fullname" . }}
        - name: html-files
          emptyDir: {}
