apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "matomo.labels" . | indent 4 }}
type: Opaque
data:
  {{- range .Values.secrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
